### PR TITLE
Add missing equals and hashCode

### PR DESCRIPTION
**Pull request by mr-zepol**

### CODE REVIEW

**Comment by skhokhlov** [comment]
@mr-zepol thank you for this!

**Comment by skhokhlov** [comment]
@nscuro can we ask for a new release version with this changes?

**Comment by nscuro** [comment]
I think @mr-zepol is still in the process of making changes, so not sure if we're in a release-ready state at the moment.

**Comment by mr-zepol** [comment]
> I think @mr-zepol is still in the process of making changes, so not sure if we're in a release-ready state at the moment.

Those are nice to have ( just raised the last PR), but a new release can be done without them

**Comment by nscuro** [comment]
Thanks @mr-zepol! PR is merged, I'll ask Steve to publish a new release.

**Comment by nscuro** [comment]
https://github.com/CycloneDX/cyclonedx-core-java/releases/tag/cyclonedx-core-java-9.0.3

**Pull request merged**
