### PR TITLE
Support CycloneDX 1.6.1

### LINKED ISSUE #551: Support CycloneDX 1.6.1
see https://github.com/CycloneDX/specification/releases/tag/1.6.1

### PR DESCRIPTION
**Pull request by jkowalleck**
fixes #551

- fetched latest schema from `https://github.com/CycloneDX/specification/blob/1.6.1/schema/bom-1.6*`
- fetched latest tests from `https://github.com/CycloneDX/specification/tree/master/tools/src/test/resources/1.6`

### CODE REVIEW

**Comment by jkowalleck** [comment]
some tests seam to fail.

I am not familiar with this setup and the Java implementation. 
Could you help me out, @stevespringett, @nscuro,

**Comment by mr-zepol** [comment]
> #551

I can help checking this

**Comment by mr-zepol** [comment]
@jkowalleck Test issues fixed

**Comment by mr-zepol** [comment]
SInce I made some changes it does not make sense I approve, but they look good to me

**Review by nscuro — APPROVED** [review]

**Pull request merged**
