### PR TITLE
Fix Env vars de/serialization for formulation

### PR DESCRIPTION
**Pull request by mr-zepol**
This PR introduces key improvements following extensive testing across various scenarios.

It addresses issues with the de/serialization process for formulation, particularly in handling environment variables, which were previously inconsistent. To resolve these issues, a new class structure has been implemented that better aligns with the schema definition.

**Note**: This update includes some breaking changes. However, given the nature of the changes, they are unlikely to impact current usage, as no related issues have been reported thus far.

### CODE REVIEW

**Comment by mr-zepol** [comment]
Fixed Compilation Issues

**Comment by nscuro** [comment]
> @mr-zepol Note: This update includes some breaking changes. However, given the nature of the changes, they are unlikely to impact current usage, as no related issues have been reported thus far.

While I technically agree, I do think we need to take semver a bit more seriously. Last time we released breaking changes in a bugfix version (by my mistake). So I'd suggest we bump the library version to `10.0.0-SNAPSHOT` for this: 

https://github.com/CycloneDX/cyclonedx-core-java/blob/dde00242ae0271e38a0e4312fad0136d801f219c/pom.xml#L26

WDYT?

**Comment by mr-zepol** [comment]
> > @mr-zepol Note: This update includes some breaking changes. However, given the nature of the changes, they are unlikely to impact current usage, as no related issues have been reported thus far.
> 
> While I technically agree, I do think we need to take semver a bit more seriously. Last time we released breaking changes in a bugfix version (by my mistake). So I'd suggest we bump the library version to `10.0.0-SNAPSHOT` for this:
> 
> https://github.com/CycloneDX/cyclonedx-core-java/blob/dde00242ae0271e38a0e4312fad0136d801f219c/pom.xml#L26
> 
> WDYT?

Yes, that makes sense, so IMO what we should do is merge the other PRs we have, have a normal release, and then this one

**Comment by mr-zepol** [comment]
> @mr-zepol Good suggestion!

So I will create smaller PRs for this one that we can merge before introducing the actual breaking changes, so we have a release with all the improvements.

**Comment by mr-zepol** [comment]
@nscuro since we have a new release with the previous changes, this one can be merged now

**Review by nscuro — APPROVED** [review]

**Pull request merged**
