### PR TITLE
Code Improvements

### PR DESCRIPTION
**Pull request by mr-zepol**
This PR:

- Reduce code duplication
- Polish code

### CODE REVIEW

**Review by nscuro — APPROVED** [review]

**Comment by stevespringett** [comment]
Could you resolve the conflicts on this?

**Comment by mr-zepol** [comment]
> Could you resolve the conflicts on this?

Sure, looking into it

**Comment by mr-zepol** [comment]
> Could you resolve the conflicts on this?

@stevespringett conflicts resolved

**Comment by stevespringett** [comment]
Looks like the last merge with the license corrections created yet another conflict.

**Comment by mr-zepol** [comment]
> Looks like the last merge with the license corrections created yet another conflict.

@stevespringett I resolved the conflicts

**Pull request merged**
