### PR TITLE
Add more license mappings

### LINKED ISSUE #212: More licenses need to be recognized
Some projects don't declare their license conform to the SPDX standard. So CycloneDX can't determine which license the project is using, this result in additional efforts for manual auditing. Because of this, i need more license mappings. I will provide a PR for this.

**Need some aliases for**
- Apache-2.0
- BSD-2-Clause
- BSD-3-Clause
- CC0-1.0
- GPL-2.0-with-classpath-exception
- LGPL-2.1-only

Please see #213 for details.

### PR DESCRIPTION
**Pull request by tmehnert**
I have added more license mappings. I would appreciate if you could take a look at the PR.

This PR Resolve #212

### CODE REVIEW

**Comment by stevespringett** [comment]
Thanks for the PR. @msymons any concerns?

**Comment by msymons** [comment]
The concern about mapping of "The BSD License" to `BSD-4-Clause` rather than to `BSD-4-Clause` has not yet been resolved. See #205 with my comment added 5th June 2022.

For new mappings added in this PR I would say "Looks OK but I do not have examples to hand to judge otherwise".

One thing I can see in my Dependency-Track v4.6.0 SNAPSHOT, displaying BOMs generated by latest version of `cyclonedx-maven-plugin` is that it is very visible when a mapping has not YET been done.  Here is one example:

#### "ASF 2.0",  which should map to Apache-2.0

Example: https://repo1.maven.org/maven2/cglib/cglib-parent/3.3.0/cglib-parent-3.3.0.pom

I also see unmapped:

* GNU Lesser Public License
* GNU LESSER GENERAL PUBLIC LICENSE

...but how far do you want to go with mapping?  ie,  would it be useful for me to dig out additional examples?

**Comment by tmehnert** [comment]
@stevespringett it would be nice, if we can get this PR done. If any concerns left, just tell me and i will more research as you wish.

**Comment by stevespringett** [comment]
Thanks again for the PR @tmehnert. Much appreciated.

**Pull request merged**
